//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace MyWindowsApplication.MyDbProxy {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tungSqlServerProxySoap", Namespace="http://tempuri.org/")]
    public class tungSqlServerProxyWse : Microsoft.Web.Services2.WebServicesClientProtocol {
        
        /// <remarks/>
        public tungSqlServerProxyWse() {
            this.Url = "http://localhost/MyService/tungSqlServerProxy.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet(string query) {
            object[] results = this.Invoke("fSelectAndFillDataSet", new object[] {
                        query});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet2(string query, string srcTable) {
            object[] results = this.Invoke("fSelectAndFillDataSet2", new object[] {
                        query,
                        srcTable});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet2(string query, string srcTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet2", new object[] {
                        query,
                        srcTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet3(string query, int startRecord, int maxRecords, string srcTable) {
            object[] results = this.Invoke("fSelectAndFillDataSet3", new object[] {
                        query,
                        startRecord,
                        maxRecords,
                        srcTable});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet3(string query, int startRecord, int maxRecords, string srcTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet3", new object[] {
                        query,
                        startRecord,
                        maxRecords,
                        srcTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteNonQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int fExecuteNonQuery(string query) {
            object[] results = this.Invoke("fExecuteNonQuery", new object[] {
                        query});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteNonQuery(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteNonQuery", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndfExecuteNonQuery(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteScalar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object fExecuteScalar(string query) {
            object[] results = this.Invoke("fExecuteScalar", new object[] {
                        query});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteScalar(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteScalar", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndfExecuteScalar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteXmlReader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XmlReader fExecuteXmlReader(string query) {
            object[] results = this.Invoke("fExecuteXmlReader", new object[] {
                        query});
            return ((XmlReader)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteXmlReader(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteXmlReader", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public XmlReader EndfExecuteXmlReader(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((XmlReader)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tungSqlServerProxySoap", Namespace="http://tempuri.org/")]
    public class tungSqlServerProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public tungSqlServerProxy() {
            this.Url = "http://localhost/MyService/tungSqlServerProxy.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet(string query) {
            object[] results = this.Invoke("fSelectAndFillDataSet", new object[] {
                        query});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet2(string query, string srcTable) {
            object[] results = this.Invoke("fSelectAndFillDataSet2", new object[] {
                        query,
                        srcTable});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet2(string query, string srcTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet2", new object[] {
                        query,
                        srcTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet2(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fSelectAndFillDataSet3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet fSelectAndFillDataSet3(string query, int startRecord, int maxRecords, string srcTable) {
            object[] results = this.Invoke("fSelectAndFillDataSet3", new object[] {
                        query,
                        startRecord,
                        maxRecords,
                        srcTable});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfSelectAndFillDataSet3(string query, int startRecord, int maxRecords, string srcTable, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fSelectAndFillDataSet3", new object[] {
                        query,
                        startRecord,
                        maxRecords,
                        srcTable}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndfSelectAndFillDataSet3(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteNonQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int fExecuteNonQuery(string query) {
            object[] results = this.Invoke("fExecuteNonQuery", new object[] {
                        query});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteNonQuery(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteNonQuery", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndfExecuteNonQuery(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteScalar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object fExecuteScalar(string query) {
            object[] results = this.Invoke("fExecuteScalar", new object[] {
                        query});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteScalar(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteScalar", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndfExecuteScalar(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fExecuteXmlReader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public XmlReader fExecuteXmlReader(string query) {
            object[] results = this.Invoke("fExecuteXmlReader", new object[] {
                        query});
            return ((XmlReader)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfExecuteXmlReader(string query, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("fExecuteXmlReader", new object[] {
                        query}, callback, asyncState);
        }
        
        /// <remarks/>
        public XmlReader EndfExecuteXmlReader(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((XmlReader)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract class XmlReader {
    }
}
